/*
   This file has been generated by IDA.
   It contains local type definitions from
   AC2-Win64-Shipping.i64
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >;
struct rapidjson::GenericMember<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >;
struct rapidjson::CrtAllocator;
struct rapidjson::GenericStringBuffer<rapidjson::UTF16<wchar_t>,rapidjson::CrtAllocator>;
struct rapidjson::PrettyWriter<rapidjson::GenericStringBuffer<rapidjson::UTF16<wchar_t>,rapidjson::CrtAllocator>,rapidjson::UTF16<wchar_t>,rapidjson::UTF16<wchar_t>,rapidjson::CrtAllocator,0>;
struct UDPPacket;
struct ksRacing::WritableRaceStructureVtbl;

/* 62365 */
struct __cppobj std::allocator<wchar_t>
{
};

/* 57829 */
struct __cppobj std::_Container_base0
{
};

/* 201518 */
typedef unsigned __int16 wchar_t;

/* 62366 */
union std::_String_val<std::_Simple_types<wchar_t> >::_Bxty
{
  wchar_t _Buf[8];
  wchar_t *_Ptr;
  char _Alias[8];
};

/* 62367 */
struct __cppobj std::_String_val<std::_Simple_types<wchar_t> > : std::_Container_base0
{
  std::_String_val<std::_Simple_types<wchar_t> >::_Bxty _Bx;
  unsigned __int64 _Mysize;
  unsigned __int64 _Myres;
};

/* 62368 */
struct __cppobj std::_Compressed_pair<std::allocator<wchar_t>,std::_String_val<std::_Simple_types<wchar_t> >,1> : std::allocator<wchar_t>
{
  std::_String_val<std::_Simple_types<wchar_t> > _Myval2;
};

/* 62369 */
struct std::_String_alloc<std::_String_base_types<wchar_t,std::allocator<wchar_t> > >
{
  std::_Compressed_pair<std::allocator<wchar_t>,std::_String_val<std::_Simple_types<wchar_t> >,1> _Mypair;
};

/* 62376 */
struct __cppobj std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > : std::_String_alloc<std::_String_base_types<wchar_t,std::allocator<wchar_t> > >
{
};

/* 67188 */
struct ksRacing::WritableRaceStructure
{
  ksRacing::WritableRaceStructureVtbl *vfptr;
  std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > fileDir;
};

/* 67209 */
struct __cppobj ksRacing::DriverInfo : ksRacing::WritableRaceStructure
{
  std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > firstName;
  std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > secondName;
  std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > lastName;
  std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > nickName;
  std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > shortName;
  char weight;
  __declspec(align(2)) _BYTE nationality[2];
  _BYTE driverCategory[1];
  std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > driverRow;
  int helmetTemplateKey;
  int helmetBaseColor;
  int helmetDetailColor;
  char helmetMaterialType;
  int helmetGlassColor;
  float helmetGlassMetallic;
  int glovesTemplateKey;
  int suitTemplateKey;
  int suitDetailColor1;
  int suitDetailColor2;
  char skillLevel;
  char aggroLevel;
  std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > playerID;
};

/* 67207 */
struct ksRacing::WritableRaceStructureVtbl
{
  void *(__cdecl *__vecDelDtor)(ksRacing::WritableRaceStructure *this, unsigned int);
  void (__cdecl *ValidateStruct)(ksRacing::WritableRaceStructure *this);
  void (__cdecl *JsonToStruct)(ksRacing::WritableRaceStructure *this, rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > *);
  void (__cdecl *StructToJson)(ksRacing::WritableRaceStructure *this, rapidjson::PrettyWriter<rapidjson::GenericStringBuffer<rapidjson::UTF16<wchar_t>,rapidjson::CrtAllocator>,rapidjson::UTF16<wchar_t>,rapidjson::UTF16<wchar_t>,rapidjson::CrtAllocator,0> *);
  void (__cdecl *writePacket)(ksRacing::WritableRaceStructure *this, UDPPacket *);
  void (__cdecl *readFromPacket)(ksRacing::WritableRaceStructure *this, UDPPacket *);
};

/* 67189 */
struct rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::String
{
  unsigned int length;
  unsigned int hashcode;
  const wchar_t *str;
};

/* 67190 */
struct rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::ShortString
{
  wchar_t str[7];
};

/* 67191 */
struct rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::Number::I
{
  int i;
  char padding[4];
};

/* 67192 */
struct rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::Number::U
{
  unsigned int u;
  char padding2[4];
};

/* 67193 */
union rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::Number
{
  rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::Number::I i;
  rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::Number::U u;
  __int64 i64;
  unsigned __int64 u64;
  long double d;
};

/* 67196 */
struct rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::ObjectData
{
  unsigned int size;
  unsigned int capacity;
  rapidjson::GenericMember<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > *members;
};

/* 67197 */
struct rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::ArrayData
{
  unsigned int size;
  unsigned int capacity;
  rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > *elements;
};

/* 67198 */
struct rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::Flag
{
  char payload[14];
  unsigned __int16 flags;
};

/* 67199 */
union rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::Data
{
  rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::String s;
  rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::ShortString ss;
  rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::Number n;
  rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::ObjectData o;
  rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::ArrayData a;
  rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::Flag f;
};

/* 67194 */
struct rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >
{
  rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::Data data_;
};

/* 67201 */
struct rapidjson::internal::Stack<rapidjson::CrtAllocator>
{
  rapidjson::CrtAllocator *allocator_;
  rapidjson::CrtAllocator *ownAllocator_;
  char *stack_;
  char *stackTop_;
  char *stackEnd_;
  unsigned __int64 initialCapacity_;
};

/* 67203 */
struct __declspec(align(4)) rapidjson::Writer<rapidjson::GenericStringBuffer<rapidjson::UTF16<wchar_t>,rapidjson::CrtAllocator>,rapidjson::UTF16<wchar_t>,rapidjson::UTF16<wchar_t>,rapidjson::CrtAllocator,0>
{
  rapidjson::GenericStringBuffer<rapidjson::UTF16<wchar_t>,rapidjson::CrtAllocator> *os_;
  rapidjson::internal::Stack<rapidjson::CrtAllocator> level_stack_;
  int maxDecimalPlaces_;
  bool hasRoot_;
};

/* 3753 */
enum rapidjson::PrettyFormatOptions
{
  kFormatDefault = 0x0,
  kFormatSingleLineArray = 0x1,
};

/* 67204 */
struct __cppobj __declspec(align(8)) rapidjson::PrettyWriter<rapidjson::GenericStringBuffer<rapidjson::UTF16<wchar_t>,rapidjson::CrtAllocator>,rapidjson::UTF16<wchar_t>,rapidjson::UTF16<wchar_t>,rapidjson::CrtAllocator,0> : rapidjson::Writer<rapidjson::GenericStringBuffer<rapidjson::UTF16<wchar_t>,rapidjson::CrtAllocator>,rapidjson::UTF16<wchar_t>,rapidjson::UTF16<wchar_t>,rapidjson::CrtAllocator,0>
{
  wchar_t indentChar_;
  unsigned int indentCharCount_;
  rapidjson::PrettyFormatOptions formatOptions_;
};

/* 61932 */
struct $BD85036DCC0442AA317E9171D0F2179B
{
  char s_b1;
  char s_b2;
  char s_b3;
  char s_b4;
};

/* 61933 */
struct $CC608A129C88F312E26B04B0A6BA5EDC
{
  unsigned __int16 s_w1;
  unsigned __int16 s_w2;
};

/* 61934 */
union $B6F142B416B8E9EC191D20324079D3AD
{
  $BD85036DCC0442AA317E9171D0F2179B S_un_b;
  $CC608A129C88F312E26B04B0A6BA5EDC S_un_w;
  unsigned int S_addr;
};

/* 61935 */
struct in_addr
{
  $B6F142B416B8E9EC191D20324079D3AD S_un;
};

/* 61936 */
struct sockaddr_in
{
  unsigned __int16 sin_family;
  unsigned __int16 sin_port;
  in_addr sin_addr;
  char sin_zero[8];
};

/* 67205 */
struct IPAddress
{
  sockaddr_in sokaddr;
};

/* 67206 */
struct UDPPacket
{
  IPAddress targetIP;
  char *data;
  unsigned int currentDataPos;
  unsigned int size;
};

/* 67195 */
struct rapidjson::GenericMember<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >
{
  rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > name;
  rapidjson::GenericValue<rapidjson::UTF16<wchar_t>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > value;
};

/* 67202 */
struct rapidjson::GenericStringBuffer<rapidjson::UTF16<wchar_t>,rapidjson::CrtAllocator>
{
  rapidjson::internal::Stack<rapidjson::CrtAllocator> stack_;
};

/* 67200 */
struct __cppobj rapidjson::CrtAllocator
{
};

