#pragma once

// Assetto Corsa Competizione (0.1.0) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ACC_ABP_lamborghini_gallardo_rex_exterior_classes.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function ABP_lamborghini_gallardo_rex_exterior.ABP_lamborghini_gallardo_rex_exterior_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_E0AD0C454204368F99471593F0F790D8
struct UABP_lamborghini_gallardo_rex_exterior_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_E0AD0C454204368F99471593F0F790D8_Params
{
};

// Function ABP_lamborghini_gallardo_rex_exterior.ABP_lamborghini_gallardo_rex_exterior_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_9F68624B41A09324C09226A328427EF4
struct UABP_lamborghini_gallardo_rex_exterior_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_9F68624B41A09324C09226A328427EF4_Params
{
};

// Function ABP_lamborghini_gallardo_rex_exterior.ABP_lamborghini_gallardo_rex_exterior_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_27A464B64A072BAEF551B1B163419D6C
struct UABP_lamborghini_gallardo_rex_exterior_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_27A464B64A072BAEF551B1B163419D6C_Params
{
};

// Function ABP_lamborghini_gallardo_rex_exterior.ABP_lamborghini_gallardo_rex_exterior_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_10949F254D6D03BD14392EA998A34EF9
struct UABP_lamborghini_gallardo_rex_exterior_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_10949F254D6D03BD14392EA998A34EF9_Params
{
};

// Function ABP_lamborghini_gallardo_rex_exterior.ABP_lamborghini_gallardo_rex_exterior_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_SequenceEvaluator_5029D2204103B9CF613DC5837099486F
struct UABP_lamborghini_gallardo_rex_exterior_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_SequenceEvaluator_5029D2204103B9CF613DC5837099486F_Params
{
};

// Function ABP_lamborghini_gallardo_rex_exterior.ABP_lamborghini_gallardo_rex_exterior_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_SequencePlayer_4684F9CE45AE661BB12394B595312B29
struct UABP_lamborghini_gallardo_rex_exterior_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_SequencePlayer_4684F9CE45AE661BB12394B595312B29_Params
{
};

// Function ABP_lamborghini_gallardo_rex_exterior.ABP_lamborghini_gallardo_rex_exterior_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_SequencePlayer_1DF00ECD490C9F3B5D98F08BD21D1437
struct UABP_lamborghini_gallardo_rex_exterior_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_SequencePlayer_1DF00ECD490C9F3B5D98F08BD21D1437_Params
{
};

// Function ABP_lamborghini_gallardo_rex_exterior.ABP_lamborghini_gallardo_rex_exterior_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_A7CE9D8642A418EA2B382BBCA55E76EA
struct UABP_lamborghini_gallardo_rex_exterior_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_A7CE9D8642A418EA2B382BBCA55E76EA_Params
{
};

// Function ABP_lamborghini_gallardo_rex_exterior.ABP_lamborghini_gallardo_rex_exterior_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_A9054C3246CCDA45346D3E9629249B53
struct UABP_lamborghini_gallardo_rex_exterior_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_A9054C3246CCDA45346D3E9629249B53_Params
{
};

// Function ABP_lamborghini_gallardo_rex_exterior.ABP_lamborghini_gallardo_rex_exterior_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_D872C38E48D10DB5042D3CA16C8AAE29
struct UABP_lamborghini_gallardo_rex_exterior_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_D872C38E48D10DB5042D3CA16C8AAE29_Params
{
};

// Function ABP_lamborghini_gallardo_rex_exterior.ABP_lamborghini_gallardo_rex_exterior_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_2DD992824EAA3F378A8AA18350A0346C
struct UABP_lamborghini_gallardo_rex_exterior_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_2DD992824EAA3F378A8AA18350A0346C_Params
{
};

// Function ABP_lamborghini_gallardo_rex_exterior.ABP_lamborghini_gallardo_rex_exterior_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_19904124450E67ECB66146B128DC6C28
struct UABP_lamborghini_gallardo_rex_exterior_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_19904124450E67ECB66146B128DC6C28_Params
{
};

// Function ABP_lamborghini_gallardo_rex_exterior.ABP_lamborghini_gallardo_rex_exterior_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_2D5DBB83443C6A7A910DF4B804BE83A3
struct UABP_lamborghini_gallardo_rex_exterior_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_2D5DBB83443C6A7A910DF4B804BE83A3_Params
{
};

// Function ABP_lamborghini_gallardo_rex_exterior.ABP_lamborghini_gallardo_rex_exterior_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_592B90A24B25D1E4885042992B1FEA9E
struct UABP_lamborghini_gallardo_rex_exterior_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_592B90A24B25D1E4885042992B1FEA9E_Params
{
};

// Function ABP_lamborghini_gallardo_rex_exterior.ABP_lamborghini_gallardo_rex_exterior_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_A4FF6E2B43DDE1A268E3018FCC94C35B
struct UABP_lamborghini_gallardo_rex_exterior_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_A4FF6E2B43DDE1A268E3018FCC94C35B_Params
{
};

// Function ABP_lamborghini_gallardo_rex_exterior.ABP_lamborghini_gallardo_rex_exterior_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_B6CD5183446D25A9EEF4219FC5A23C2E
struct UABP_lamborghini_gallardo_rex_exterior_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_B6CD5183446D25A9EEF4219FC5A23C2E_Params
{
};

// Function ABP_lamborghini_gallardo_rex_exterior.ABP_lamborghini_gallardo_rex_exterior_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_C8613D974D120BB16598B2995E399964
struct UABP_lamborghini_gallardo_rex_exterior_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_C8613D974D120BB16598B2995E399964_Params
{
};

// Function ABP_lamborghini_gallardo_rex_exterior.ABP_lamborghini_gallardo_rex_exterior_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_6CF73A1C4AD398D902695F9ED66BAD1B
struct UABP_lamborghini_gallardo_rex_exterior_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_6CF73A1C4AD398D902695F9ED66BAD1B_Params
{
};

// Function ABP_lamborghini_gallardo_rex_exterior.ABP_lamborghini_gallardo_rex_exterior_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_TransitionResult_848B088A45897CF17378A38D0340ACFB
struct UABP_lamborghini_gallardo_rex_exterior_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_TransitionResult_848B088A45897CF17378A38D0340ACFB_Params
{
};

// Function ABP_lamborghini_gallardo_rex_exterior.ABP_lamborghini_gallardo_rex_exterior_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_47D2E78E49A4BD87D27BA68D72454ED0
struct UABP_lamborghini_gallardo_rex_exterior_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_AnimGraphNode_ModifyBone_47D2E78E49A4BD87D27BA68D72454ED0_Params
{
};

// Function ABP_lamborghini_gallardo_rex_exterior.ABP_lamborghini_gallardo_rex_exterior_C.ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior
struct UABP_lamborghini_gallardo_rex_exterior_C_ExecuteUbergraph_ABP_lamborghini_gallardo_rex_exterior_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
